### ISSUE TITLE
iOS, Cannot Sync application.

### ISSUE THREAD

**Issue by Sitheps** [jfokus/bug-reporting#1]
It is not possible for me or my colleagues to sync the iOS application using the link in the email or trhough your website,.

**Comment by podal** [comment]
Whats happen when you press the link? Sometimes there is an box at the top of webpage say somerhing like go to ’Jfokus Conference’

**Comment by Sitheps** [comment]
Hey,
 More of a design flaw then a bug.  When you follow link you end up in mid
of page, but button to launch app and sync it only shows when you scroll to
top of page in a tiny window. Took a while but we found it eventually.


mån 4 feb. 2019 kl. 09:46 skrev Thomas Podal <notifications@github.com>:

**Comment by podal** [comment]
Unfortunately, this is the way Apple design it.

**Comment by ennru** [comment]
Last year's issue. Let's make room for issues in the new app...
